= snowplow-browser-plugin-recaptcha-assessment

A
https://snowplowanalytics.com/[Snowplow]
https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/[JavaScript Tracker]
https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/javascript-tracker-v3/plugins/[plugin]
to enable catching
https://www.google.com/recaptcha/about/[ReCAPTCHA]
https://developers.google.com/recaptcha/docs/v3#interpreting_the_score[user scores]
for site traffic.

The approach is similar to https://www.simoahava.com/analytics/improve-google-analytics-bot-detection-with-recaptcha/[this article],
but without the need for a PHP service to verify the token.
This role is performed by the Snowplow Enricher instead, via a https://docs.snowplowanalytics.com/docs/enriching-your-data/available-enrichments/custom-javascript-enrichment/[Custom JavaScript enrichment].

== Requirements
As the ReCAPTCHA tokens expire after about 2 minutes, the enrichment will only work on a real time, streaming pipeline.
Processing historical events won't successfully enrich the data.

The plugin requires the Snowplow JavaScript tracker version 3.

== Setup
=== Schemas
There are three Self Describing JSON definitions you will need to deploy to your pipeline's Iglu Server from the `schemas` directory:

  . `com.google.recaptcha/action` for the event or context generated on the user device (associated with an https://developers.google.com/recaptcha/docs/v3#actions["action"]) and used as input to the API
  . `com.google.recaptcha/assessment` for the API assessment result, including the score (not required if only using ReCAPTCHA Enterprise)
  . `com.google.recaptcha/enterprise_assessment` for the API assessment result, including the score (only required if using ReCAPTCHA Enterprise)

=== ReCAPTCHA v3
. You will need to have a site configured in https://www.google.com/recaptcha/admin[ReCAPTCHA]. The site settings should give you a _Site Key_ and _Secret Key_

. Edit the enrichment configuration (`recaptcha_enrich.js`):

  - For standard ReCAPTCHA v3:
    .. In the top config block, replace `CHANGEME` in the `secretKey` config with your ReCAPTCHA API _Secret Key_
    .. Make sure `enterprise` is set to `false`

  - For ReCAPTCHA Enterprise:
    .. In the top config block, set `enterprise` to `true`
    .. Set `gcpProject` to the Project ID your ReCAPTCHA Enterprise API belongs to. If it is the same as your enrichment pipeline, you can leave it as `null` to be detected automatically. This must be the numeric project ID, not the text project name.
    .. For `secretKey`, set the value to either:
      * a https://console.cloud.google.com/apis/credentials[Google Cloud API Key]
      * Empty string (`""`), `CHANGEME`, or `null` to use the Enricher instance's Service Account to request an Access Token (GCP only, see below)

    .. Change `gcpServiceAccount` to the Service Account available on your enricher instance to request an access token for. The default is to use the default instance Service Account.
    .. You must specify either an API Key in `secretKey` or use a `gcpServiceAccount` (`default` or otherwise) to use ReCAPTCHA Enterprise.

. Generate and install the enrichment:
    .. Run `npm install`. This will generate an enrichment configuration in `dist/recaptcha_enrich.json` with your authentication included.
    .. Load the generated configuration into your enrichers `enrichments` directory and restart the enricher

. The `npm install` command will also minify the plugin code for you, into `dist/recaptcha_assessment.js`.
  Upload the plugin, and install it into your tracking code:
  - As an external plugin:
[source,javascript]
snowplow(
	'addPlugin',
	'https://cdn.example.com/recaptcha_assessment.js',
	['recaptcha_assessment', 'default'],
	[{siteKey: '<SITE KEY>', enterprise: false}]
);
  - Inline:
[source,javascript]
// include recaptcha_assessment.js already
snowplow( 'addPlugin', recaptcha_assessment, 'default', [{siteKey: '<SITE KEY>', enterprise: false}]);

=== hCaptcha Enterprise Support
As the API for https://www.hcaptcha.com/[hCaptcha] is very similar, it is also supported with the following configuration changes:

. Use the `com.hcaptcha` schema variants instead of `com.google.recaptcha`
. Specify the `hCaptcha: true` setting when loading the plugin and configuring the enricher, and a hCaptcha `siteKey`

For hCaptcha, only https://docs.hcaptcha.com/faq/#what-are-the-difficulty-levels-for-the-challenges-and-how-are-they-selected["Passive"] captchas are supported. This requires https://www.hcaptcha.com/enterprise[hCaptcha Enterprise].
You can enable Passive Mode in the Site Settings within hCaptcha, by changing the "Captcha difficulty" slider to "Passive".
Even though this is an Enterprise API, the `enterprise` and `hCaptcha` settings are mutually exclusive.

Note if you change an existing site key configuration from a different mode to Passive, it may still issue challenges to users.
Archiving and Unarchiving the Site configuration seems to fix this.

== Plugin Parameters
As demonstrated above, the plugin takes a single parameter: an `object` with the following parameters:

siteKey::
The ReCAPTCHA/hCaptcha _Site Key_ to generate a token for. *Required* `string`
enterprise::
If enabled, use the ReCAPTCHA Enterprise APIs instead of the free version. _Default: false_ `boolean`
hCaptcha::
Shorthand config to enable hCaptcha support rather than Google ReCAPTCHA. This changes the defaults for other settings to be compatible with hCaptcha. _Default: false_ `boolean`
action::
The value to use for the "action" property in the event or context. _Default: page_view_ `string`
sendContext::
If enabled, send the `action` payload as a context on the first event sent once the payload is available. _Default: true_ `boolean`
sendEvent::
If enabled, send the `action` payload as a Self Describing Event once the payload is available. _Default: false_ `boolean`
schema::
The schema to use when sending the `action` payload. Useful if you need to make changes to the schema. _Default: iglu:com.google.recaptcha/action/jsonschema/1-0-0 or iglu:com.hcaptcha/challenge/jsonschema/1-0-0_ `string`
altDomain::
Whether to use an https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally[alternative domain] to load the API library script from. If `true`, uses `www.recaptcha.net`, if a string, uses that as the domain. If unset or falsy, uses the default `www.google.com` or `js.hcaptcha.com` for hCaptcha. _Default: undefined (www.google.com/js.hcaptcha.com)_ `boolean / string`
pathPrefix::
URL path segment to use when loading the API library. _Default: /recaptcha/ (ReCAPTCHA) or /1/ (hCaptcha)_ `string`
params::
Object detailing any additional parameters to include in the API library URL. _Default: empty object_ `object`
callback::
A function to call with the token value once received in case you want to do something else with it `function`

=== sendContext vs sendEvent
The context approach is useful if you already have a high volume of events or use late-firing events like https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/javascript-tracker-v3/tracking-events/#activity-tracking-page-pings[Page Pings] already. This will make the overall impact on your data collection minimal, as it will not have the overhead of an additional event firing, but if no events fire after the payload is available you may not capture the data.

The event approach is useful if you don't care about event volume, or are more concerned about not having the recaptcha score (this avoids any races where all events might be sent before the action payload is available).
